Update Readme.md
Patfarmurs/budgetapp pull request #5
Opened 2023-08-17 23:28 UTC by Patfarmurs

## In this PR  
>- I create a Ruby on Rails application that allows the user to:
>- Register and log in, so that the data is private to them.
>- Introduce new transactions associated with a category.
>- See the money spent on each category.
>- I create unit and integration tests for all the most important components of my RoR application.

2023-08-18 02:06 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @Patfarmurs, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

<img src="https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- List of transaction is presented ordered by most recent as requested :+1: 
- Great job for making use of Rails partials to keep your codebase DRY :+1: 
- Unit tests runs without errors :+1: 

## Required Changes ♻️

- [ ] **Video Presentation:** As suggested in the requirements, kindly make sure to record a professional video presentation of the features of your project. The maximum length should be 5 minutes. The presentation should contain a clear and objective description about the project in a professional English. Topic and purpose of the project should be made clear. The video contains a demo of the project highlighting all the project features and kindly make sure to highlight a piece of code you are proud of making.
- [ ] **Live Version** Kindly make sure to deploy the application properly, with all the pages working as expected :+1: 

_Check the comments under the review._

## Optional suggestions
**N/A**
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-08-18 02:06 UTC, FrederickMih commented on README.md
> +# 💰 budgetapp <a name="about-project"></a>
> **I'll leave comments using your README file because most of your changes were not constantly committed to your repo hence I can't point to a particular line of code**

- [x] Since this is a web _mobile_ application, kindly make sure the home page is responsive. A responsive web app enables users to have a better experience while using the app irrespective of the device size :+1: As can be seen below, the name of the app, signup, signin are all close together.

![Screenshot from 2023-08-18 01-48-26](https://github.com/Patfarmurs/budgetapp/assets/63087491/7723f8e6-2b62-4695-9b1b-864f70e4fe52)

2023-08-18 02:06 UTC, FrederickMih commented on README.md
> +# 💰 budgetapp <a name="about-project"></a>
- [x] Kindly make sure to follow the design guidelines as requested(color, layout and topography)

| Guidelines | Yours |
| --- | --- |
| ![Screenshot from 2023-08-18 02-19-12](https://github.com/Patfarmurs/budgetapp/assets/63087491/f2f70a8c-e9c0-4005-a71d-6f1b8326eff5) | ![Screenshot from 2023-08-18 02-12-24](https://github.com/Patfarmurs/budgetapp/assets/63087491/9701187e-4f12-4424-b4f2-386d5bb737ac) |

- [x] An icon or a link to the categories field are not working. You may use a file upload system for that specific. 
- [x] A friendly reminder: The button `New category` should be found at the bottom of the page as you can see on the design above :arrow_up: 
- [x] A friendly reminder: It would be nice to include validation messages when creating a category for the purpose of great user experience(When I tried to submit empty fields, no error messages show up)

2023-08-18 02:06 UTC, FrederickMih commented on README.md
> +# 💰 budgetapp <a name="about-project"></a>
- [x] Kindly make sure the button _Add new transaction_ is at the bottom of the page as requested. As a friendly reminder, please use the same font as in the design guidelines

2023-08-18 02:06 UTC, FrederickMih commented on README.md
> +# 💰 budgetapp <a name="about-project"></a>
- [x] `routes.rb file` In order to minimized memory usage, let's kindly use only necessary routes. You didn't implement the `destroy` action hence there's no need to include this in your routes for both` transfers` and `groups` as you can see below:

 ```
 resources :groups, only: [:index, :new, :create, :destroy] do
    resources :transfers, only: [:index, :new, :create, :show, :destroy] 
 end
```

2023-08-18 02:06 UTC, FrederickMih commented on README.md
> +# 💰 budgetapp <a name="about-project"></a>
- Lastly, kindly update the title of your PR to make it more descriptive and in line with your project.

2023-08-18 18:16 UTC, Patfarmurs commented on README.md
> +# 💰 budgetapp <a name="about-project"></a>
Thanks, @FrederickMih Icon and link to the categories field are working on my end.

2023-08-18 18:20 UTC, Patfarmurs commented on README.md
> +# 💰 budgetapp <a name="about-project"></a>
Hi @FrederickMih I don't want to mess up anything since it's already Friday haha! , I can remove them later.

2023-08-19 18:31 UTC, tugsem approved these changes
## STATUS: APPROVED ✔️ 
Hi @Patfarmurs , 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![Alt Text](https://media.giphy.com/media/3o6Ztp6SgDdzR0XD2w/giphy.gif)
Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-08-19 18:46 UTC, Patfarmurs commented
Thank you @tugsem.

2023-08-19 18:46 UTC, merged